project:
  title: "BIOINF 576"
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  repo-url: https://github.com/kelly-sovacool/bioinf576-ci
  site-url: https://sovacool.dev/bioinf576-ci
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@kelly_sovacool"
  open-graph: true
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        url: https://github.com/kelly-sovacool/bioinf576-ci

execute:
  freeze: auto

title-block-banner: true
title-block-style: default
author: 
  name: Kelly Sovacool
  url: https://sovacool.dev
format:
  html:
    theme: spacelab
    toc: true
    toc-depth: 5
    toc-location: left
    date-format: iso
    embed-resources: true
    code-line-numbers: true
    code-link: true
    code-overflow: wrap

